### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-app-php#5]
### Motivation

In order to be able to check whether the application builds with every submitted PR, we'd like to set up CI.

### Proposed solution

Set up CI using Travis: https://travis-ci.org/Kentico/kentico-cloud-sample-app-php

**Comment by Simply007** [comment]
CD set to: https://dashboard.heroku.com/apps/kontent-sample-app-php

Use devrel credentials from password server.

Live is here http://kontent-sample-app-php.herokuapp.com

**Comment by Simply007** [comment]
CI set here:
https://github.com/Kentico/kontent-sample-app-php/actions

**Comment by petrsvihlik** [comment]
good job :)
