### ISSUE TITLE
Make the site work with the latest version of Laravel Framework

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-app-php#6]
### Motivation

Make sure the site is up to date with the latest standards.

### Proposed solution

Update Laravel to v5.7.x.

**Comment by shennawy** [comment]
Is running composer update and then rerunning the tests good enough for this issue?

**Comment by petrsvihlik** [comment]
@shennawy The site must not return any runtime errors when it's run: https://github.com/Kentico/kentico-cloud-sample-app-php/#application-setup


I moved the issue to: https://github.com/Kentico/kentico-cloud-sample-app-php/issues/8 (this one seems to be broken for me)
