### ISSUE TITLE
App doesn't work on php 7.3

### ISSUE THREAD

**Issue by Fantom409** [Kentico/kontent-sample-app-php#9]
### Brief bug description

What went wrong?

I got exception when run this app on PHP 7.3

### Repro steps

1. Install application
2. Browse application

### Expected behavior

What the correct behavior is?

Correctly working application
### Test environment

PHP 7.3 (lamp stack)
Ubuntu 18.04

I got exception when I run application on php 7.3 - it's caused by Sunra's HTML DOM parser - that package doesn't support php 7.3.

I think at least information that this app doesn't support php 7.3 should be provided on README file

**Comment by petrsvihlik** [comment]
thanks @Fantom409 . I believe, we are aware of the issue, right @Simply007 ?

**Comment by Simply007** [comment]
We are currently dealing with the issue with the new HTML parser that supports PHP 7.3:
https://sourceforge.net/p/simplehtmldom/support-requests/49/

**Comment by Simply007** [comment]
@Fantom409 - would you mind to try to set the composer to use the [kontent-delivery-sdk-php v3.0](https://packagist.org/packages/kentico/kontent-delivery-sdk-php)?

**Comment by Fantom409** [comment]
Ok, I'll do it

**Comment by Simply007** [comment]
@Fantom409 - I have just found a fix of an infinite loop of destruct calls (https://sourceforge.net/p/simplehtmldom/support-requests/49/).

As a part of that, I have also merged the pull request #10  with @dusekdan.

Now the application should work on v7.3 of PHP.

**Comment by Simply007** [comment]
Feel free to reopen the issue, if I have missed anything!
